version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@5.0.2

jobs:
  build-test:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          command: |
            npm ci
            npm run build
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git:
          app-name: joke-app-iw3

workflows:
  build-and-test:
    jobs:
      - build-test
      - node/test:
          test-results-for: jest

      - deploy:
          requires:
            - "build-test"
            - "node/test"