version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-test: # this can be any name you choose
    docker:
      - image: cimg/node:16

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: Install Dependencies
          command: |
            pnpm install

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      
      - run:
          name: Build and test the app
          command: |
            pnpm build
            pnpm test

workflows:
  build-and-test:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - main